name: "collector"
version: "1.0"
main: "com.pythoncraft.collector.PluginMain"
api-version: "1.21"
authors: [pythoncraft]
description: "Collector plugin for Minecraft"
depend: [GameLib]
depends: [GameLib]

commands:
  collector:
    description: "Collector command"
    usage: "/collector [items|deaths] <time>"
  compass:
    description: "Get a tracking compass"
    usage: "/compass [<player>]"
